# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjVIKG3b4BJ3O1QMQgZ-ru98oIe2AlzO
"""

!pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/blastchar/telco-customer-churn")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8')
sns.set_palette('colorblind')
pd.set_option('display.max_columns', None)

# Loading $ Cleaning the datasets

print("Loading Customer retention and Churn analysis data")
df = pd.read_csv("/content/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")
print (f"Original shape of the dataset: {df.shape}")
print(df.head())

# Information
print(f"Data information:")
print(df.info())

# Cleaning the datasets

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] =df['TotalCharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
df['Tenure_group'] = pd.cut(df['tenure'], bins=[-1, 12, 24, 48, 100] , labels=['0-12 months','13-24 months', '25-48 months','49+ months'])
df['Monthly_charge'] = pd.cut(df['MonthlyCharges'], bins = [0,40,70,200], labels = ['low(<40$)','medium(40$-70$)','high(>70$)'])

# Extra Services Provided
extra_ser = ['OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV', 'StreamingMovies']
df['num_ser'] = df[extra_ser].apply(lambda x: sum(x=='Yes'), axis =1)
df['has_multiple_ser'] = (df['num_ser']>=3).astype(int)
print("Clean data shape" , df.shape)
print(df[['tenure','Tenure_group','Monthly_charge','TotalCharges','Churn']].head())

# Retension and Churn
overall_churn =df['Churn'].mean() *100
print(f"Overall churn rate: {overall_churn:.2f}%")
tenure_churn = df.groupby('Tenure_group',observed=True)['Churn'].agg(['mean','count']).round(4)
tenure_churn['mean'] = tenure_churn['mean']*100
print("Tenure churn mean rate:")
print(tenure_churn)
print("Retained Customer vs Churn Customer: ")
print(df.groupby('Churn')[['tenure', 'MonthlyCharges','TotalCharges']].mean().round(2))

# Cohort Analysis

print("Cohort Analysis")
Contract_churn = df.groupby('Contract')['Churn'].agg(['mean','count'])
Contract_churn['mean'] = Contract_churn['mean']*100
print("Churn contract")
print(Contract_churn.round(2))
Intrenet_churn = df.groupby('InternetService')['Churn'].agg(['mean','count'])
Intrenet_churn['mean'] = Intrenet_churn['mean']*100
print("Internet Churn")
print(Intrenet_churn.round(2))
Payment_churn = df.groupby('PaymentMethod')['Churn'].agg(['mean','count'])
Payment_churn['mean'] = Payment_churn['mean']*100
print("Payment Churn")
print(Payment_churn.round(2))
Extra_churn = df.groupby('has_multiple_ser')['Churn'].agg(['mean','count'])
Extra_churn['mean'] = Extra_churn['mean']*100
print("Extra Churn")
print(Extra_churn.round(2))

# Visualizations of the Analysis

fig , axes = plt.subplots(2,2, figsize=(15,10))
sns.barplot(x=tenure_churn.index, y= tenure_churn['mean'], ax =axes[0,0], hue=tenure_churn.index, palette = 'viridis', legend=False)
axes[0,0].set_title('Churn Tenure Rate')
axes[0,0].set_xlabel('Tenure')
axes[0,0].set_ylabel('Churn Rate')
for container in axes[0,0].containers:
    axes[0,0].bar_label(container , fmt='%.2f%%')
sns.barplot(x=Contract_churn.index, y= Contract_churn['mean'], ax =axes[0,1], hue=Contract_churn.index, palette = 'viridis', legend=False)
axes[0,1].set_title('Churn Contract Rate')
axes[0,1].set_ylabel('Contract')
for container in axes [0,1].containers:
    axes[0,1].bar_label(container , fmt='%.2f%%')
sns.barplot(x=Intrenet_churn.index, y= Intrenet_churn['mean'], ax =axes[1,0])
axes[1,0].set_title('Churn Internet Rate')
axes[1,0].set_ylabel('Churn Rate')
for container in axes[1,0].containers:
  axes[1,0].bar_label(container, fmt='%.1f%%')
sns.barplot(x=Payment_churn.index, y= Payment_churn['mean'],ax=axes[1,1])
axes[1,1].set_title('Payment Churn')
axes[1,1].set_ylabel('Churn Rate')
for container in axes[1,1].containers:
  axes[1,1].bar_label(container,fmt='.1f%%')
plt.tight_layout()
plt.show()

# Retention curve

Tenure_retention = 1 - df.groupby('Tenure_group',observed=True)['Churn'].mean()
plt.figure(figsize=(10,6))
plt.plot(Tenure_retention.index, Tenure_retention, label = 'Retention Rate', color='red')
plt.title('Retention Curve')
plt.xlabel('Tenure')
plt.ylabel('Retention Probability')
plt.grid(True)
plt.legend()
plt.show()

# Key Summary or Insights from the Analysis

print("\n" + "="*60)
print("Key Summary or Insights from the Analysis")
print("=" *60)
print(f"1. Overall Churn Rate: {overall_churn:.2f}%")
print(f"2. Highest Risk Cohorts: {tenure_churn.idxmax()}")
print(f"3. Most Powerful lever: {Contract_churn.idxmax()}")
print(f"4. Fiber optic without extra services: {Intrenet_churn.idxmax()}")
print(f"5. Payment Method: {Payment_churn.idxmax()}")
print(f"6. Extra Services: {Extra_churn.idxmax()}")
print(f"7. Retention Curve: {Tenure_retention.idxmax()}")